-- Add French translation column for trade rationale
ALTER TABLE trade_ideas 
ADD COLUMN IF NOT EXISTS rationale_fr text;

-- Add comment
COMMENT ON COLUMN trade_ideas.rationale_fr IS 'French translation of the trade rationale generated by AI';


